version: "3.3"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports: ["27017:27017"]

  storage:
    build: ./storage
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    ports: ["5004:5004"]
    depends_on: [mongo]

  score:
    build: ./score
    ports: ["5003:5003"]

  llm:
    build: ./llm_service
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports: ["5002:5002"]

  cache:
    build: ./cache
    environment:
      - CACHE_SIZE=${CACHE_SIZE:-1000}
      - CACHE_TTL=${CACHE_TTL:-0}
      - CACHE_POLICY=${CACHE_POLICY:-LRU}
      - LLM_URL=http://llm:5002/answer
      - SCORE_URL=http://score:5003/score
      - STORE_SAVE_URL=http://storage:5004/save_or_update
      - STORE_INC_URL=http://storage:5004/increment
    ports: ["5001:5001"]
    depends_on: [llm, score, storage]

  traffic:
    build: ./traffic_generator
    environment:
      - DATASET_PATH=/app/dataset/train.csv
      - RATE=${RATE:-0.2}
      - DIST=${DIST:-exponential}
      - CACHE_URL=http://cache:5001/query
      - COL_Q=question_content
      - COL_A=best_answer
    volumes:
      - ./dataset:/app/dataset:ro
    depends_on: [cache]

